services:
  server:
    image: novadityap/property-platform-server-dev
    container_name: property-platform-server-dev
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate reset --force &&
        npm run dev
      "
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./server:/app           
      - /app/node_modules  
    networks:
      - property-platform-dev

  client:
    image: novadityap/property-platform-client-dev
    container_name: property-platform-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./client/.env.development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - property-platform-dev

  postgres:
    container_name: property-platform-postgres-dev
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - property-platform-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: property_platform_dev
    networks:
      - property-platform-dev

volumes:
  property-platform-postgres-data:
    name: property-platform-postgres-data
networks:
  property-platform-dev:
    name: property-platform-dev
